OUTPUT = TestCWTime
CWUTILS = ../../../../CWUtils/C++/Linux



all:help

help:
	@echo make build
	@echo make run

build:
	clear
	clear
	clear
	g++ -o $(OUTPUT) -I$(CWUTILS) $(CWUTILS)/*.cpp *.cpp

run:
	./$(OUTPUT)
